### ISSUE TITLE
Is it possible to use with casbin new  async class?

### ISSUE THREAD

**Issue by adk23333** [thearchitector/casbin-tortoise-adapter#7]
At present, I have no problem using it like this.
```
adapter = TortoiseAdapter()
e = casbin.AsyncEnforcer('./casbin_data/model.conf', adapter)
```
Can you change the next version of asynccasbin to an optional import

**Comment by thearchitector** [comment]
hi! yes, i'm aware of the new async stuff and i plan on replacing it; that work is pending [this](https://github.com/casbin/pycasbin/issues/334), but i just have not had time to get around to either yet.

**Comment by adk23333** [comment]
> hi! yes, i'm aware of the new async stuff and i plan on replacing it; that work is pending [this](https://github.com/casbin/pycasbin/issues/334), but i just have not had time to get around to either yet.

Thank you for your job. I look forward to their new versions being released

**Comment by thearchitector** [comment]
@adk23333 i got around to adding the async stubs to `pycasbin` itself, and after some back and forth with the pycasbin folks, we have a new release of both

AsyncCasbin is replaced with PyCasbin in the latest version, so if you can update PyCasbin to 1.34, you can use version 2.0.0 of this package with the builtin AsyncEnforcer like you show above: https://github.com/thearchitector/casbin-tortoise-adapter/releases/tag/v2.0.0

**Comment by adk23333** [comment]
> @thearchitector 
> you can use version 2.0.0 of this package with the builtin AsyncEnforcer like you show above

happy new year! I will try it in my code.
